// src/Pjfm.Bff/ClientApp/src/app/modules/session/components/track-progression-bar/track-progression-bar.component.ts
import { Component, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core';

@Component({
  selector: 'pjfm-track-progression-bar',
  templateUrl: './track-progression-bar.component.html',
  styleUrls: ['./track-progression-bar.component.scss'],
})
export class TrackProgressionBarComponent implements OnInit, OnChanges {
  @Input() trackDurationMs!: number;
  @Input() startTimeMs = 0;

  private _currentInterval!: any;

  currentTimeMs!: number;
  trackPercentage = 0;

  ngOnInit(): void {
    this.reset();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.trackDurationMs && !changes.trackDurationMs.isFirstChange()) {
      this.reset();
    }
  }

  private reset(): void {
    this.currentTimeMs = this.startTimeMs;

    if (this._currentInterval != null) {
      clearInterval(this._currentInterval);
    }

    this.setTimeout();
  }

  private setTimeout(): void {
    this._currentInterval = setInterval(() => {
      if (this.currentTimeMs < this.trackDurationMs) {
        this.currentTimeMs += 1000;
        this.trackPercentage = Math.round((this.currentTimeMs / this.trackDurationMs) * 100);
      }
    }, 1000);
  }
}

<div class="container">
  <pjfm-ascii-slider [percentage]="trackPercentage"></pjfm-ascii-slider>
  <div class="time-labels-container">
    <div class="time-label">
      {{currentTimeMs | convertMsToTime}}
    </div>
    <div class="time-label">
      {{trackDurationMs | convertMsToTime}}
    </div>
  </div>
</div>

// src/Pjfm.Api/ClientApp/src/components/session/trackProgressionBar.svelte
<script lang="ts">
   import AsciiSlider from "./AsciiSlider.svelte";

   export let trackDurationMs!: number;
   export let startTimeMs = 0;
   
   let currentInterval!: any;
   let currentTimeMs!: number;
   let trackPercentage = 0;
   
   function formatTimeMs(value: number): string {
       const seconds = Math.floor(value / 1000);
       const minutes = Math.floor(seconds / 60);
       const leftOverSeconds = seconds - minutes * 60;

       return `${Math.round(minutes)}:${leftOverSeconds < 10 ? '0' : ''}${Math.round(leftOverSeconds)}`;
   }
   
   $: {
       if (trackDurationMs)
           reset();
   }
   
   function reset() {
       currentTimeMs = startTimeMs;
       
       if (currentInterval != null) {
            clearInterval(currentInterval);    
       }

       setTimeOut();
   }
   
   function setTimeOut() {
       currentInterval = setInterval(() => {
           if (currentTimeMs < trackDurationMs) {
               currentTimeMs += 1000;
               trackPercentage = Math.round((currentTimeMs  / trackDurationMs) * 100);
           }
       }, 1000);
   }
</script>

<div class="container">
    
    <AsciiSlider percentage="{trackPercentage}"></AsciiSlider>
    
    <div class="time-labels-container">
        <div class="time-label">{formatTimeMs(currentTimeMs)}</div>
        <div class="time-label">{ formatTimeMs(trackDurationMs)}</div>
    </div>
</div>
